### ISSUE TITLE
Type Exception with latest version

### ISSUE THREAD

**Issue by redmunds** [GregorBiswanger/Brackets-ZoomView#1]
I upgraded from 1.0.0 to 1.0.1 on Win7 and extension no longer works:

```
[Extension] failed to load C:/Users/redmunds/AppData/Roaming/Brackets/extensions/user/zoomview TypeError: Cannot call method 'replace' of undefined (ExtensionLoader.js:209)
errback (ExtensionLoader.js:209)
```

Recipe:
1. Open a document and verify the ZoomView dropdown says "100%"
2. Change font size using View > Increase Font Size

Result
Font size in page increase, but ZoomView dropdown still says 100%. Same for Decrease Font Size and Restore Font Size.

**Comment by GregorBiswanger** [comment]
Hi,
I used the 'replace' function in 1.0.0 too. I have no idea of this exception. It´s running on my system.
Possibly I must call this function inerhit AppInit.htmlReady?

**Comment by redmunds** [comment]
The problem is not on the 'replace' function, but that the object that you are calling it on is undefined.

**Comment by GregorBiswanger** [comment]
okay, I switched the initialization code into a function that calls from AppInit.htmlReady.
Can I send you an email with the changed extension and you can test it quickly?

**Comment by redmunds** [comment]
Sure. It's probably easiest if you put the code in a branch and I can test directly from there, then you can merge it when ready.

**Comment by GregorBiswanger** [comment]
The new experimental branch is online. I looking forward for your feedback!
https://github.com/GregorBiswanger/Brackets-ZoomView/tree/experimental

**Comment by redmunds** [comment]
I'm still seeing the same error. It looks like `PreferencesManager.getViewState("fontSizeStyle")` returns undefined when you try to retrieve it before it's ever set.

**Comment by dangoor** [comment]
@GregorBiswanger the reason it works for you and not for others is that you already have fontSizeStyle set in your viewstate (the state.json file in the directory that also has your user-installed extensions, use Help->Show Extensions Folder and then go up a level). If you delete fontSizeStyle from that file and then reload, you'll hit the same error.

It may make sense for us to define a default value for that in Brackets (@RaymondLim may have an opinion there). In the mean time, you should check the return value of `PreferencesManager.getViewState("fontSizeStyle")` before you try to use it because it could be undefined, as @redmunds is stating above.

**Comment by GregorBiswanger** [comment]
Hi@all,
I have updated my extension. Can you please test the experimental branch from here:
https://github.com/GregorBiswanger/Brackets-ZoomView/tree/experimental

**Comment by redmunds** [comment]
@GregorBiswanger I just tested your update and I am no longer seeing the exception.

I am still seeing a bug though. Your control updates when I use Ctrl-[plus] and Ctrl-[minus] to change font size every time **except** the first time! Which really sucks because it's always off after that. And it does not reset to 100% on Ctrl-0.

Let me know if you need more details.
